module.exports = [
  "What is the name of the software",
  "What is the name of the company",
  "Where is the headquarter of the company",
  "Who owns the software",
  "Who has the intellectual property of the software",
  "What are the terms of the license grant",
  "Is the product licensed or sold",
  "How long is the license",
  "How many downloads are authorized",
  "How long is the period of evaluation",
  "Is there a reverse engineering clause",
  "What are the restriction on use for users",
  "Is there any related agreements",
  "Is your application collecting personal information from users",
  "Is there a termination of licensing",
  "Is there a Maintenance Policies",
  "What is the period of warranty",
  "What is the disclaimer of warranty",
  "Is it possible that the product will be updated regularly in the future",
  "For any material changes, what is the period of time that the company has to notice the user in advance",
  "Under the law of which jurisdiction this agreement is referring to ",
  "Is there a specific export information",
];
